name: Sync Fork with Upstream

on:
  workflow_call:
    inputs:
      upstream_owner:
        required: true
        type: string

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for merging

      - name: Configure git
        run: git config --global user.name "Github Action"

      - name: Add upstream remote
        run: git remote add upstream ${{ github.server_url }}/${{ inputs.upstream_owner }}/${{ github.event.repository.name }}.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Rebase onto upstream changes
        run: |
          git checkout main
          git rebase upstream/main

      - name: Push changes to fork
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_with_lease: true
